use std::sync::Arc;

use metallic_macros::KernelArgs;

use crate::{
    Foundry, MetalError, compound::{BufferArg, CompiledCompoundKernel, CompoundKernel, Stage}, fusion::MetalPolicy, metals::embedding::{EmbeddingParams, EmbeddingParamsResolved}, spec::{CompiledStep, FastBindings, SymbolTable, TensorBindings}, types::{DispatchConfig, GridSize, TensorArg}
};

// Note: EmbeddingStep and CompiledEmbeddingStep are auto-generated by #[derive(Kernel)] in mod.rs

impl CompiledStep for super::CompiledEmbeddingStep {
    fn execute(
        &self,
        foundry: &mut Foundry,
        fast_bindings: &FastBindings,
        bindings: &TensorBindings,
        _symbols: &SymbolTable,
    ) -> Result<(), MetalError> {
        let table = fast_bindings
            .get(self.table)
            .ok_or_else(|| MetalError::InputNotFound("embedding table".into()))?;
        let indices = fast_bindings
            .get(self.indices)
            .ok_or_else(|| MetalError::InputNotFound("embedding indices".into()))?;
        let output = fast_bindings
            .get(self.output)
            .ok_or_else(|| MetalError::InputNotFound("embedding output".into()))?;

        // Derived scales: generated as `usize` index by macro via `scale_for`
        // Validation: If table is Q8, `scale_for` tensor must exist.
        // If table is F16, `scale_for` tensor might not exist (Optional in CompiledStep?).
        // Wait, I made it `TensorArg` (mandatory) in CompiledStep generation if I used regular logic.
        // But `symbols.get_or_create` ALWAYS creates an index.
        // So `self.scale_bytes` is a valid usize index.
        // `fast_bindings.get(idx)` returns `Option<&Tensor>`.
        // If unbound, it returns None.
        // Fallback to table (dummy) if None.
        let scale_bytes = fast_bindings.get(self.scale_bytes).unwrap_or(table);

        let params = EmbeddingParamsResolved {
            d_model: self.params.d_model.resolve(bindings),
            total_elements: self.params.total_elements.resolve(bindings),
            vocab_size: self.params.vocab_size.resolve(bindings),
        };

        let policy = crate::policy::resolve_policy(table.dtype.into());
        // Note: we don't use policy.loader() here, we bind directly.
        // But execute logic is consistent with creating a CompoundKernel.

        let args = EmbeddingGenericArgs {
            table: TensorArg::from_tensor(table),
            scale_bytes: TensorArg::from_tensor(scale_bytes),
            indices: TensorArg::from_tensor(indices),
            output: TensorArg::from_tensor(output),
            params,
        };

        let kernel = get_embedding_kernel(policy);
        let dispatch = DispatchConfig {
            grid: GridSize::d1(params.total_elements as usize),
            group: crate::types::ThreadgroupSize::d1(256),
        };

        foundry.run(&kernel.bind_arc(args, dispatch))?;
        Ok(())
    }

    fn name(&self) -> &'static str {
        "Embedding"
    }
}

#[derive(Debug, Clone, KernelArgs)]
pub struct EmbeddingGenericArgs {
    pub table: TensorArg,
    pub scale_bytes: TensorArg,
    pub indices: TensorArg,
    pub output: TensorArg,
    pub params: EmbeddingParamsResolved,
}

#[derive(Debug, Clone, KernelArgs)]
pub struct EmbeddingStage {
    pub params: EmbeddingParamsResolved,
    pub policy: Arc<dyn MetalPolicy>,
}

impl Stage for EmbeddingStage {
    fn includes(&self) -> Vec<&'static str> {
        // Policy header MUST come before embedding.metal since the template uses Policy types
        vec![self.policy.header(), "embedding/embedding.metal"]
    }

    fn buffer_args(&self) -> Vec<BufferArg> {
        vec![
            BufferArg {
                name: "table",
                metal_type: "const device uchar*",
                buffer_index: 0,
            },
            BufferArg {
                name: "scale_bytes",
                metal_type: "const device uchar*",
                buffer_index: 1,
            },
            BufferArg {
                name: "indices",
                metal_type: "const device uint*",
                buffer_index: 2,
            },
            BufferArg {
                name: "output",
                metal_type: "device half*",
                buffer_index: 3,
            },
            BufferArg {
                name: "params",
                metal_type: "constant EmbeddingParams*",
                buffer_index: 4,
            },
        ]
    }

    fn emit(&self, _input_var: &str) -> (String, String) {
        let code = format!(
            r#"
    run_embedding_core<{policy}>(table, scale_bytes, indices, output, params, gid.x);
"#,
            policy = self.policy.struct_name()
        );
        ("output".to_string(), code)
    }

    fn struct_defs(&self) -> String {
        EmbeddingParams::METAL_STRUCT_DEF.to_string()
    }
}

pub fn get_embedding_kernel(policy: Arc<dyn MetalPolicy>) -> Arc<CompiledCompoundKernel> {
    use crate::kernel_registry::{KernelCacheKey, kernel_registry};

    let variant = policy.short_name().to_string();
    let key = KernelCacheKey::new("embedding", variant);

    kernel_registry().get_or_build(key, || {
        let dummy_params = EmbeddingParamsResolved {
            d_model: 0,
            total_elements: 0,
            vocab_size: 0,
        };
        let stage = EmbeddingStage {
            params: dummy_params,
            policy: policy.clone(),
        };

        let kernel_name = format!("embedding_standalone_{}", policy.short_name());
        CompoundKernel::new(&kernel_name).main(stage).with_manual_output(true).compile()
    })
}
